### ISSUE TITLE
Networking question

### ISSUE THREAD

**Issue by sudo-kraken** [dwedia/podmanQuadlets#1]
In the gluetun folder, you have a vpnstack.network, but no network entries in deluge or gluetun how is the vpnstack.network picked up by these containers?

I also have a second question for example you run NPM or a proxy as rootful i.e. npm.service and npm.network, how can you ensure that rootless containers can communicate back and forth with this container?

**Comment by dwedia** [comment]
Hi, sorry for the late response. 

I never got my VPN stack working as Quadlets.
I haven't had the time to work on it since I edited it last. I use podman-compose with the compose file over in my podman-files repo, here: [vpnstack Compose file](https://github.com/dwedia/podman-files/blob/main/vpnStack/compose.yml).

As for your second question, it is not something I have tested, so I can't help you there, sorry...

**Comment by dwedia** [comment]
See comment here: https://github.com/dwedia/podmanQuadlets/issues/1#issuecomment-2496218146

**Comment by dwedia** [comment]
See comment here: https://github.com/dwedia/podmanQuadlets/issues/1#issuecomment-2496218146

**Comment by redbeardymcgee** [comment]
@sudo-kraken I have been working on making quadlets more accessible for users, and I think I can answer your question.

Define your `vpnstack.network` and then in the `gluetun.container` add `Network=vpnstack.network` under the `[Container]` section. I am running with a `protonvpn.network` like this. Now you can talk to any other container by `ContainerName` or `HostName` (not sure which, I always make them the same right now) as long as they also have the same `Network=vpnstack.network`. To route traffic through the `gluetun` container, you can then set `some-app-behind-gluetun.container` with `Network=container:gluetun`.

https://github.com/redbeardymcgee/podbox is where I'm working on dozens of examples.

@dwedia Would you be interested in contributing more container examples? I have borrowed some inspiration from your repo already.

**Comment by dwedia** [comment]
@redbeardymcgee Well, Ill be damned... Your suggestion worked =)

I just tested with just a gluetun container and a deluge container, and the deluge container connected through the gluetun container =).. 

This is the unit file for my gluetun container
```bash
[Unit]
Description=Gluetun Quadlet

[Container]
Image=docker.io/qmcgaw/gluetun:latest
ContainerName=Gluetun-Quadlet
HostName=Gluetun-Quadlet
AddCapability=NET_ADMIN

PodmanArgs=--privileged --device /dev/net/tun --dns 1.1.1.1

EnvironmentFile=secrets.txt
EnvironmentFile=gluetun.env


PublishPort=8112:8112
PublishPort=6881:6881
PublishPort=6881:6881/udp


Volume=/opt/podmnts/gluetun/config:/gluetun:Z


[Service]
Restart=always
TimeoutStartSec=900

[Install]
WantedBy=multi-user.target default.target
```

The deluge container:
```bash
[Unit]
Description=Deluge Quadlet
Requires=gluetun.service

[Container]
Image=lscr.io/linuxserver/deluge:latest
ContainerName=Deluge-Quadlet
HostName=Deluge-Quadlet

Environment=TimeZone=Europe/Copenhagen
Environment=DELUGE_LOGLEVEL=error

PodmanArgs=-e PUID=1000 -e PGID=1000 

Volume=/opt/podmnts/sabnzbd/config:/config:Z
Volume=/opt/netmounts/new/Torrents/Complete/:/downloads
Volume=/opt/netmounts/new/Torrents/Incomplete/:/Incomplete

Network=container:Gluetun-Quadlet

[Service]
Restart=always
TimeoutStartSec=900

[Install]
WantedBy=multi-user.target default.target
```

The vpnstack.network unit file:
```bash
[Network]
Subnet=192.168.99.0/24
Gateway=192.168.99.1
Label=app=vpnstack
Driver=bridge
```

Thanks, I am now off to make unit files for the rest of the services I want to run in this stack =)

About contributing, I have a hard time just finding time to do all the projects I want to do on my own, so I do not want to agree to anything, sorry.
But you are more than welcome to grab anything you think you can use from my repos =)

I also post stuff about the things i put in my repo (amongst other things), on my [blog / website](https://dragonflight.dk/)

**Comment by sudo-kraken** [comment]
@dwedia thank you for your input I cracked this a little while after I posted this issue, sorry I only just saw this. I would love to contribute to this or @redbeardymcgee if either of you guys want some input I have a fair few things running successfully now.

**Comment by sudo-kraken** [comment]
> @redbeardymcgee Well, Ill be damned... Your suggestion worked =)
> 
> I just tested with just a gluetun container and a deluge container, and the deluge container connected through the gluetun container =)..
> 
> This is the unit file for my gluetun container
> 
> ```shell
> [Unit]
> Description=Gluetun Quadlet
> 
> [Container]
> Image=docker.io/qmcgaw/gluetun:latest
> ContainerName=Gluetun-Quadlet
> HostName=Gluetun-Quadlet
> AddCapability=NET_ADMIN
> 
> PodmanArgs=--privileged --device /dev/net/tun --dns 1.1.1.1
> 
> EnvironmentFile=secrets.txt
> EnvironmentFile=gluetun.env
> 
> 
> PublishPort=8112:8112
> PublishPort=6881:6881
> PublishPort=6881:6881/udp
> 
> 
> Volume=/opt/podmnts/gluetun/config:/gluetun:Z
> 
> 
> [Service]
> Restart=always
> TimeoutStartSec=900
> 
> [Install]
> WantedBy=multi-user.target default.target
> ```
> 
> The deluge container:
> 
> ```shell
> [Unit]
> Description=Deluge Quadlet
> Requires=gluetun.service
> 
> [Container]
> Image=lscr.io/linuxserver/deluge:latest
> ContainerName=Deluge-Quadlet
> HostName=Deluge-Quadlet
> 
> Environment=TimeZone=Europe/Copenhagen
> Environment=DELUGE_LOGLEVEL=error
> 
> PodmanArgs=-e PUID=1000 -e PGID=1000 
> 
> Volume=/opt/podmnts/sabnzbd/config:/config:Z
> Volume=/opt/netmounts/new/Torrents/Complete/:/downloads
> Volume=/opt/netmounts/new/Torrents/Incomplete/:/Incomplete
> 
> Network=container:Gluetun-Quadlet
> 
> [Service]
> Restart=always
> TimeoutStartSec=900
> 
> [Install]
> WantedBy=multi-user.target default.target
> ```
> 
> The vpnstack.network unit file:
> 
> ```shell
> [Network]
> Subnet=192.168.99.0/24
> Gateway=192.168.99.1
> Label=app=vpnstack
> Driver=bridge
> ```
> 
> Thanks, I am now off to make unit files for the rest of the services I want to run in this stack =)
> 
> About contributing, I have a hard time just finding time to do all the projects I want to do on my own, so I do not want to agree to anything, sorry. But you are more than welcome to grab anything you think you can use from my repos =)
> 
> I also post stuff about the things i put in my repo (amongst other things), on my [blog / website](https://dragonflight.dk/)

Also nice blog!!
